# Generated by Django 4.0.7 on 2023-08-16 12:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, verbose_name='اسم')),
                ('keywords', models.CharField(max_length=255, verbose_name='گلمه کلیدی')),
                ('description', models.TextField(max_length=255, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='تصویر')),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10, verbose_name='وضعیت')),
                ('slug', models.SlugField(unique=True, verbose_name='آدرس')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='category.category', verbose_name='زیر مجموعه')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
