version : "3.7"

services:
  app:
    build: './app'
    container_name: 'app'
    restart: 'always'
    expose:
      - '8000'
    volumes:
      - type: 'bind'
        source: './volumes/mysite'
        target: '/mysite'


  nginx:
    build: './nginx'
    container_name: 'nginx'
    restart: 'always'
    ports:
      - "7001:7001"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezne:ro"
      - type: 'bind'
        source: './volumes/mysite/media'
        target: '/mysite/media'

      - type: 'bind'
        source: './volumes/static'
        target: '/mysite/static'
