# Generated by Django 4.0.7 on 2024-06-01 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_shippingcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.shippingcost'),
            preserve_default=False,
        ),
    ]
