# Generated by Django 4.0.7 on 2023-12-07 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_images_image_alter_product_image'),
        ('users', '0002_alter_myuser_first_name_alter_myuser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReturnModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('دیده نشده', 'دیده نشده'), ('در حال بررسی', 'در حال بررسی'), ('تایید شده تماس میگیریم', 'تایید شده تماس میگیریم')], max_length=100)),
                ('image', models.ImageField(null=True, upload_to='ProductReturn')),
                ('image1', models.ImageField(null=True, upload_to='ProductReturn')),
                ('image2', models.ImageField(null=True, upload_to='ProductReturn')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
