# Generated by Django 4.0.7 on 2024-02-27 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_bugbounty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bugbounty',
            old_name='desctiption',
            new_name='text',
        ),
    ]
