# Generated by Django 4.0.7 on 2024-05-28 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=150, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='price',
            field=models.CharField(max_length=150, verbose_name='قیمت'),
        ),
    ]
