# Generated by Django 4.0.7 on 2023-08-14 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_created_at_product_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
    ]
