# Generated by Django 4.0.7 on 2023-12-16 19:00

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_images_image_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='data',
            field=jsonfield.fields.JSONField(null=True, verbose_name='دیتا'),
        ),
    ]
