# Generated by Django 4.0.7 on 2024-03-03 13:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=255, verbose_name='توضیحات'),
        ),
    ]
