# Generated by Django 4.0.7 on 2024-03-03 21:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='description_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='description_image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
