# Generated by Django 4.0.7 on 2024-03-07 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_description_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='guarantee',
            field=models.CharField(choices=[('18 ماه گارانتی شرکتی', '18 ماه گارانتی شرکتی')], default=1, max_length=100, verbose_name='گارانتی'),
            preserve_default=False,
        ),
    ]
