# Generated by Django 4.0.7 on 2024-03-07 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_guarantee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='guarantee',
        ),
    ]
